import './globals.scss'
import {Inter} from 'next/font/google'

import AppContainer from "@/components/AppContainer";
import {Icon} from "@iconify/react";

const inter = Inter({subsets: ['latin']})
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: any) {
    return (
            <html lang="en">
                <body className={inter.className}>
                    {/* eslint-disable-next-line react/no-children-prop */}
                    <AppContainer children={props.children}/>
                </body>
            </html>
    )
}
